FROM python:3.10-slim

ENV PYTHONUNBUFFERED 1

RUN mkdir /opt/code
RUN mkdir /opt/requirements

COPY requirements.txt /opt/requirements/requirements.txt
RUN apt-get update && \
    pip install -r /opt/requirements/requirements.txt

WORKDIR /opt/code
CMD [ "flask", "run", "--host", "0.0.0.0" ]

EXPOSE 5000